kind: Secret
apiVersion: v1
metadata:
  name: mysql-petclinic
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
data:
  database-name: cGV0Y2xpbmlj
  database-password: cGV0Y2xpbmlj
  database-root-password: cGV0Y2xpbmlj
  database-user: cGV0Y2xpbmlj
type: Opaque
